export enum Page{
    START,
    MAIN
}

export enum Messages{
    SUCCESS,
    FAILURE,
    TOFG_VIDEO_ON_SCREEN,
    TOFG_CREATE_ROOM_IN_TAB,
    TOFG_JOIN_ROOM_IN_TAB,
    TOFG_DISCONNECT,
    TOFG_RETRIEVE_ROOM_DATA,
    TOFG_DO_YOU_EXIST,
    TOPOPUP_LEAVE_ROOM,
    TOPOPUP_ROOM_DATA,
    TOBG_USER_CONNECTED,
    TOFG_IS_CHANNEL_OPEN,
    TOBG_USER_DISCONNECTED
}

export const TabsStorage = "active_tabs_watchparty"
