export enum Page{
    START,
    MAIN
}

export enum Messages{
    SUCCESS,
    FAILURE,
    TOFG_VIDEO_ON_SCREEN,
    TOFG_CREATE_ROOM_IN_TAB,
    TOFG_JOIN_ROOM_IN_TAB,
    TOFG_DISCONNECT,
    TOFG_RETRIEVE_ROOM_DATA,
    TOFG_DO_YOU_EXIST,
    TOFG_SYNC_VID,
    TOPOPUP_LEAVE_ROOM,
    TOPOPUP_ROOM_DATA,
    TOFG_IS_CHANNEL_OPEN,
    TOFG_CHAT_TOGGLE,
    TOFG_SET_OFFSET,
    TOBG_OPEN_TAB_WITH_URL,
    TOFG_GET_ADMIN_VID_TIME,
    TOPOPUP_ADMIN_VID_TIME_INFO
}
